### ISSUE TITLE
Add translation option

### ISSUE THREAD

**Issue by crashzk** [Bara/Discord-MapNotification#1]
First of all congratulations for the work, I use it in my CSGO & Discord Servers, very useful, thanks for sharing.

# SUGGESTION
It would be very interesting if you put the option to include translations for the plugin to send the messages in the Discord, thus giving more freedom to the users.

Currently the messages he sends are those in print: https://i.imgur.com/6xM6f2I.png
- Now playing
- Players Online
- Quick Join

**Comment by 8guawong** [comment]
> First of all congratulations for the work, I use it in my CSGO & Discord Servers, very useful, thanks for sharing.
> 
> # SUGGESTION
> It would be very interesting if you put the option to include translations for the plugin to send the messages in the Discord, thus giving more freedom to the users.
> 
> Currently the messages he sends are those in print: https://i.imgur.com/6xM6f2I.png
> 
> * Now playing
> * Players Online
> * Quick Join

you can only translate in-game 
no way of knowing what language the discord channel uses

**Comment by crashzk** [comment]
I would have it, I believe. Just make the plugin create a config with this information, just like it did with `MapNotification_LastMap.ini` or `Discord.cfg`.

https://github.com/Bara/Discord-MapNotification/blob/1172abbdba8603a93c813a60f0866ffe74dfc80e/scripting/discord_MapNotification.sp#L119-L121

Users would be able to change to their languages ​​if they wish.

**Comment by Bara** [comment]
I added this feature, but english is still the default language. This isn't tested, but should work (if not, let me know).
