### ISSUE TITLE
Footer message improvements

### ISSUE THREAD

**Issue by crashzk** [Bara/Discord-MapNotification#10]
![image](https://github.com/Bara/Discord-MapNotification/assets/32937653/cadb7e70-4585-42ec-b836-8df603bbdbd5)

I believe we can put an option to configure a message along with the time I send the message, something customized by a cvar.

Something similar to what you have here. From sourcebans it sends hostname and IP information.
![image](https://github.com/Bara/Discord-MapNotification/assets/32937653/1aec48ce-3464-4d27-a616-e6dfd02a91b1)

However, it would be interesting to have a cvar so that we can control which message to send along with the time. It would look something like this, for example.

```
ZK Servidores™ - %time
```
As I mentioned, the message we configure in the cvar, the time is sent automatically.

**Comment by crashzk** [comment]
An observation, I don't know if it's possible but it would be interesting that the server IP that is sent in the message is a link, where the user can click to connect to the server.

**Comment by crashzk** [comment]
Strange that in the preview I send the message it shows exactly how I wanted to configure it. But I wanted it to be customizable, as I mentioned, so we can choose the message by cvar let's say.

![image](https://github.com/Bara/Discord-MapNotification/assets/32937653/43d22f45-93e9-4c40-a728-822038ba4d82)

**Comment by Bara** [comment]
Title and Footer is now configurable 👍🏻

**Comment by crashzk** [comment]
Everything working, thank you!
