### ISSUE TITLE
Connect/IP server message link option

### ISSUE THREAD

**Issue by crashzk** [Bara/Discord-MapNotification#11]
I don't know if it's possible but it would be interesting that the server IP that is sent in the message is a link, where the user can click to connect to the server.

![image](https://github.com/Bara/Discord-MapNotification/assets/32937653/e1436e7d-7d2c-4d83-9cb8-4c847aa9932a)

**Comment by Bara** [comment]
`steam://` will not detected as link. Just `http(s)://`. 
![image](https://github.com/Bara/Discord-MapNotification/assets/17928280/ca8cae43-3e97-4c42-9190-5b3c54d5577f)

I could add a simple html site which redirect to the `steam://` url.

**Comment by crashzk** [comment]
Could it be, could you make it get the server's IP instead of `Connect`?

If it does, it would be good, otherwise you can just leave it connected.

**Comment by Bara** [comment]
![image](https://github.com/Bara/Discord-MapNotification/assets/17928280/4c7511e0-75e6-4829-bb09-03f40f806311)
like this?

**Comment by Bara** [comment]
I pushed a commit with working connect link (incl. redirect.php)

**Comment by crashzk** [comment]
Perfect, test everything here. Thanks!

**Comment by crashzk** [comment]
Everything working, thank you!
