### ISSUE TITLE
Update Discord API

### ISSUE THREAD

**Issue by crashzk** [Bara/Discord-MapNotification#6]
I believe I can switch to this [Discord API](https://github.com/KillStr3aK/discord-api) as the current one apparently will no longer be supported.

https://github.com/KillStr3aK/discord-api

This new API, according to the documentation if you only want to send webhooks in your plugin, you don't need to run the main plugin, just include discord.

**Comment by crashzk** [comment]
https://github.com/Cruze03/discord-api-Killstr3ak/blob/main/discord_api.smx

I tested with this version but I get the following error:
```
Errors:
discord_MapNotification.smx ([Discord] Map Notifications): Native "DiscordWebHook.Send" was not found
 ```

**Comment by Bara** [comment]
I switched to [DiscordWebhookAPI](https://github.com/Sarrus1/DiscordWebhookAPI)/[RIPExt](https://github.com/ErikMinekus/sm-ripext) within [this commit](https://github.com/Bara/Discord-MapNotification/commit/8eadc6f1160d2ab2aeef16960f347bc9a50ec9ef), so this can be closed.
