### ISSUE TITLE
Doesn't show gametracker map image in messages

### ISSUE THREAD

**Issue by crashzk** [Bara/Discord-MapNotification#7]
Recently, map notifications on discord are no longer displaying the gametracker map image.

![image](https://user-images.githubusercontent.com/32937653/235376602-6c19de19-12cb-4f70-a281-d00f74510a98.png)

Is anyone else facing this problem? Any fixes?

**Comment by crashzk** [comment]
More recent versions send the message, but without the GameTracker map image yet, I believe it is something in the GameTracker itself.

I also noticed that there are these errors in the server log even though the plugin is sending messages to discord.
```
L 05/04/2023 - 19:54:18: [discord_MapNotification.smx] [Discord.OnWebHookExecuted] An error has occured while sending the webhook. Status Code: 200
```

**Comment by Rushaway** [comment]
After few test i can said, gametracker blocked the request from discord API. 
About the error you should use `if (response.Status != HTTPStatus_OK)` instead of `if (response.Status != HTTPStatus_NoContent)`

**Comment by crashzk** [comment]
> After few test i can said, gametracker blocked the request from discord API. About the error you should use `if (response.Status != HTTPStatus_OK)` instead of `if (response.Status != HTTPStatus_NoContent)`

Thanks for the help, I'll test this change and see if it stops the messages in the error log.

About the gametracker blocking the Discord API request, in this case we can only wait for the gametracker right? Wait to see if they take this blocked out.

Thanks in any case.
