### ISSUE TITLE
Implement time I send the message on discord

### ISSUE THREAD

**Issue by crashzk** [Bara/Discord-MapNotification#9]
Currently messages are sent like this:
![image](https://github.com/Bara/Discord-MapNotification/assets/32937653/9034739f-d596-4485-bb35-b019df48689d)

It would be something like this, send the date and time in the message as a footer. This way we can have a better control of the time that the server map changed.

![image](https://github.com/Bara/Discord-MapNotification/assets/32937653/f916fdce-b272-479f-8dc9-d94c013ecfa7)

**Comment by Rushaway** [comment]
I did it like that.
```
/* Header */
Embed Embed_1 = new Embed(sHostname);
Embed_1.SetTimeStampNow();
Embed_1.SetColor(Color);
```
[...]
```
EmbedFooter Footer = new EmbedFooter("");
Footer.SetIconURL("https://github.githubassets.com/images/icons/emoji/unicode/1f55c.png?v8");
Embed_1.SetFooter(Footer);
delete Footer;
```

**Comment by Bara** [comment]
Both has been added in recent commits. Let me know if you've other suggestions. 👍🏻 

Preview:
![Preview](https://raw.githubusercontent.com/Bara/Discord-MapNotification/master/preview.png)
